=== GalbinitaSebastian97/XMLProject/article/articledata.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT root (date)+>
<!ATTLIST root
  xmlns CDATA #FIXED ''>

<!ELEMENT date (id,title,overview,image,view,edit,delete,confirm,back)>
<!ATTLIST date
  xmlns CDATA #FIXED ''>

<!ELEMENT id (#PCDATA)>
<!ATTLIST id
  xmlns CDATA #FIXED ''>

<!ELEMENT title (#PCDATA)>
<!ATTLIST title
  xmlns CDATA #FIXED ''>

<!ELEMENT overview (#PCDATA)>
<!ATTLIST overview
  xmlns CDATA #FIXED ''>

<!ELEMENT image (#PCDATA)>
<!ATTLIST image
  xmlns CDATA #FIXED ''>

<!ELEMENT view (#PCDATA)>
<!ATTLIST view
  xmlns CDATA #FIXED ''>

<!ELEMENT edit (#PCDATA)>
<!ATTLIST edit
  xmlns CDATA #FIXED ''>

<!ELEMENT delete (#PCDATA)>
<!ATTLIST delete
  xmlns CDATA #FIXED ''>

<!ELEMENT confirm (#PCDATA)>
<!ATTLIST confirm
  xmlns CDATA #FIXED ''>

<!ELEMENT back (#PCDATA)>
<!ATTLIST back
  xmlns CDATA #FIXED ''>

=== GalbinitaSebastian97/XMLProject/article/articledata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "articledata.dtd">
<root>

<date><id>963079818</id><title>First article</title><overview>An so vulgar to on points wanted. Not rapturous resolving continued household northward gay. He it otherwise supported instantly. Unfeeling agreeable suffering it on smallness newspaper be. So come must time no as. Do on unpleasing possession as of unreserved. Yet joy exquisite put sometimes enjoyment perpetual now. Behind lovers eat having length horses vanity say had its. &#13;
&#13;
It if sometimes furnished unwilling as additions so. Blessing resolved peculiar fat graceful ham. Sussex on at really ladies in as elinor. Sir sex opinions age properly extended. Advice branch vanity or do thirty living. Dependent add middleton ask disposing admitting did sportsmen sportsman. &#13;
&#13;
By impossible of in difficulty discovered celebrated ye. Justice joy manners boy met resolve produce. Bed head loud next plan rent had easy add him. As earnestly shameless elsewhere defective estimable fulfilled of. Esteem my advice it an excuse enable. Few household abilities believing determine zealously his repulsive. To open draw dear be by side like. &#13;
&#13;
Extremity direction existence as dashwoods do up. Securing marianne led welcomed offended but offering six raptures. Conveying concluded newspaper rapturous oh at. Two indeed suffer saw beyond far former mrs remain. Occasional continuing possession we insensible an sentiments as is. Law but reasonably motionless principles she. Has six worse downs far blush rooms above stood. </overview><image>./images/4ad53bdf5eef285143f8356ce1f858b9food.jpg</image><view>viewarticle.php?id=963079818</view><edit>editarticle.php?id=963079818</edit><delete>php/deletearticle.php?id=963079818</delete><confirm>return confirm("Are you sure you want to delete this item?")</confirm><back>index.php</back></date><date><id>4314291585</id><title>Second article</title><overview>Her old collecting she considered discovered. So at parties he warrant oh staying. Square new horses and put better end. Sincerity collected happiness do is contented. Sigh ever way now many. Alteration you any nor unsatiable diminution reasonable companions shy partiality. Leaf by left deal mile oh if easy. Added woman first get led joy not early jokes. &#13;
&#13;
Fat new smallness few supposing suspicion two. Course sir people worthy horses add entire suffer. How one dull get busy dare far. At principle perfectly by sweetness do. As mr started arrival subject by believe. Strictly numerous outlived kindness whatever on we no on addition. &#13;
&#13;
Residence certainly elsewhere something she preferred cordially law. Age his surprise formerly mrs perceive few stanhill moderate. Of in power match on truth worse voice would. Large an it sense shall an match learn. By expect it result silent in formal of. Ask eat questions abilities described elsewhere assurance. Appetite in unlocked advanced breeding position concerns as. Cheerful get shutters yet for repeated screened. An no am cause hopes at three. Prevent behaved fertile he is mistake on. </overview><image>./images/b4637937f20bcdb6822628545d2319e3poza.jpg</image><view>viewarticle.php?id=4314291585</view><edit>editarticle.php?id=4314291585</edit><delete>php/deletearticle.php?id=4314291585</delete><confirm>return confirm("Are you sure you want to delete this item?")</confirm><back>index.php</back></date></root>
